<script setup lang="ts">
useSeoMeta({ title: 'An independent product studio', description: 'WUSLA is an independent software company based in Kerala, building original applications and partnering on client products.' });
const principles = [
  { title: 'Stay close to the problem.', copy: 'Understand what people are trying to do before deciding what the software should be.' },
  { title: 'Make decisions together.', copy: 'Keep product thinking, design, and engineering close enough to inform one another.' },
  { title: 'Care beyond the first release.', copy: 'Build with future changes in mind. Make room to learn from the people who use the product.' },
];
</script>
<template><div><section class="page-opening studio-container"><p class="eyebrow">The company</p><h1>Independent minds.<br><span>Useful software.</span></h1><p>WUSLA is a product studio based in Kerala, India. We build applications of our own and partner with businesses on software that matters.</p></section>
<section class="studio-container company-feature"><img src="/assets/studio-form.webp" alt="A continuous emerald sculpture, representing connected product thinking" width="1200" height="800" fetchpriority="high"><div><h2>Product thinking.<br><span>All the way through.</span></h2><p>Making our own products keeps us engaged with the same questions our clients face: what deserves to be built, how it should work, and what comes next.</p><p>We bring that perspective to web platforms, mobile applications, desktop software, and product design.</p><NuxtLink to="/capabilities" class="text-link">How we can help <span aria-hidden="true">↗</span></NuxtLink></div></section>
<section class="section-space studio-container"><div class="section-heading"><h2>The way we work<br><span>shapes what we make.</span></h2></div><div class="principle-grid"><article v-for="principle in principles" :key="principle.title"><h3>{{ principle.title }}</h3><p>{{ principle.copy }}</p></article></div></section>
<section class="studio-container practical-note"><h2>Meet us through the work.</h2><p>Explore our public projects and open-source work, or tell us about the people and problem behind your next product.</p><div class="hero-actions"><NuxtLink to="/portfolio" class="text-link">Selected work ↗</NuxtLink><a href="https://github.com/wusla-org" class="text-link" target="_blank" rel="noopener noreferrer">WUSLA on GitHub ↗</a></div></section><ProjectInvitation /></div></template>
