<script setup lang="ts">
import { ArrowUpRight } from "lucide-vue-next";
import { projects } from "~~/content/projects";
useSeoMeta({ title: "Selected work", description: "A selection of public products and platforms built with WUSLA." });
</script>

<template>
  <main class="portfolio-page"><section class="portfolio-hero"><div class="container-custom"><p>Selected public work</p><h1>Built for use,<br>not for show.</h1><div class="hero-line"><span>WUSLA has helped bring platforms, products, and useful digital experiences into the world.</span><b>01—04</b></div></div></section><section class="project-index"><div class="container-custom"><a v-for="project in projects" :key="project.num" :href="project.url" target="_blank" rel="noopener noreferrer" class="project"><span>{{ project.num }}</span><div><p>{{ project.category }}</p><h2>{{ project.name }}</h2><p class="description">{{ project.description }}</p><div class="tags"><span v-for="tag in project.tags" :key="tag">{{ tag }}</span></div></div><ArrowUpRight :size="24" /></a></div></section><section class="portfolio-close"><div class="container-custom"><p>There is more work behind the scenes. Some of it is public. Some of it is still becoming.</p><NuxtLink to="/#contact">Start a project <ArrowUpRight :size="18" /></NuxtLink></div></section></main>
</template>

<style scoped>
.portfolio-page{background:#F5FAF7;color:#093A2C}.portfolio-hero{padding:12rem 0 7rem;background:#F6F4EA}.portfolio-hero>div>p:first-child,.project>div>p:first-child{font:600 .7rem var(--font-mono);letter-spacing:.12em;text-transform:uppercase;color:#008A63}.portfolio-hero h1{font-size:clamp(3.7rem,8vw,8.5rem);line-height:.84;letter-spacing:-.09em;font-weight:720;margin:1.6rem 0 4.5rem}.hero-line{display:flex;justify-content:space-between;gap:2rem;border-top:1px solid #B8D3C5;padding-top:1rem;color:#527166}.hero-line span{max-width:29rem;line-height:1.5}.hero-line b{font:500 .7rem var(--font-mono);letter-spacing:.1em;color:#008A63}.project-index{padding:2rem 0 8rem}.project{display:grid;grid-template-columns:5rem minmax(0,1fr) 2rem;gap:2rem;padding:3.5rem 0;border-bottom:1px solid #B8D3C5;transition:padding .2s var(--ease-out)}.project:first-child{border-top:1px solid #B8D3C5}.project:hover{padding-left:1rem;background:#E7F2EC}.project>span{font:500 .75rem var(--font-mono);color:#008A63}.project h2{font-size:clamp(2.1rem,4vw,4.3rem);line-height:.95;letter-spacing:-.065em;font-weight:690;margin:1rem 0}.description{max-width:41rem;color:#527166;line-height:1.55}.tags{display:flex;flex-wrap:wrap;gap:.6rem;margin-top:1.5rem}.tags span{font:500 .68rem var(--font-mono);letter-spacing:.05em;color:#527166}.project svg{color:#008A63}.portfolio-close{padding:7rem 0;background:#006B4E;color:#F5FAF7}.portfolio-close p{max-width:26ch;font-size:clamp(2.5rem,5vw,5.5rem);line-height:.94;letter-spacing:-.07em;font-weight:680}.portfolio-close a{display:inline-flex;align-items:center;gap:.55rem;background:#D7F3E4;color:#004D38;padding:1rem 1.1rem;margin-top:2.5rem;font-weight:720}@media(max-width:767px){.portfolio-hero{padding:8rem 0 5rem}.portfolio-hero h1{margin-bottom:3rem}.project-index{padding-bottom:5rem}.project{grid-template-columns:2.5rem 1fr 1.2rem;gap:1rem;padding:2.5rem 0}.portfolio-close{padding:5rem 0}}
</style>
